publish_frequency: 1.0

footprint: [[0.32, 0.0], [0.22, 0.22], [0.0,0.25], [-0.177, 0.177], [-0.25, 0.0], [-0.177, -0.177], [0.0, -0.25], [0.22, -0.22] ]

inflation_layer:
  inflation_radius: 0.05

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 3.0
  observation_sources: front_laser front_bottom_ultra front_top_ultra left_90_ultra left_45_ultra right_90_ultra right_45_ultra 
  front_laser: {sensor_frame: rb1_base_front_laser_link, data_type: LaserScan, topic: front_laser/scan, marking: true, clearing: true, observation_persistence: 0.0}
  left_90_ultra: {topic: /biscee_ultra_cloud_left_90, marking: true, clearing: true, obstacle_range: 0.5, observation_persistence: 0.0}
  left_45_ultra: {topic: /biscee_ultra_cloud_left_45, marking: true, clearing: true, obstacle_range: 0.5, observation_persistence: 0.0}
  right_90_ultra: {topic: /biscee_ultra_cloud_right_90, marking: true, clearing: true, obstacle_range: 0.5, observation_persistence: 0.0}
  right_45_ultra: {topic: /biscee_ultra_cloud_right_45, marking: true, clearing: true, obstacle_range: 0.5, observation_persistence: 0.0}
  front_bottom_ultra: {topic: /biscee_ultra_cloud_front_bottom, marking: true, clearing: true, obstacle_range: 0.5, observation_persistence: 0.0}
  front_top_ultra: {topic: /biscee_ultra_cloud_front_top, marking: true, clearing: true, obstacle_range: 0.5, observation_persistence: 0.0}
  